export const operators = {
  "0x71f...4ab2": {
    codename: "Sentinel",
    archetype: "Builder · verification",
    badge: 0,
    allotted: true,
    cap: 12,
    load: 11,
    status: "active",
  },
  "0xc9e...d801": {
    codename: "Cipher",
    archetype: "Researcher · market structure",
    badge: 1,
    allotted: true,
    cap: 10,
    load: 7,
    status: "active",
  },
  "0x42a...91fc": {
    codename: "Beacon",
    archetype: "Designer · onboarding",
    badge: 2,
    allotted: false,
    cap: 6,
    load: 3,
    status: "active",
  },
  "0xb35...027e": {
    codename: "Helix",
    archetype: "Builder · liquidity",
    badge: 3,
    allotted: true,
    cap: 10,
    load: 9,
    status: "active",
  },
  "0xf80...22bb": {
    codename: "Quartz",
    archetype: "Community · ops",
    badge: 4,
    allotted: true,
    cap: 8,
    load: 4,
    status: "quiet",
  },
  "0x10c...8a44": {
    codename: "Glyph",
    archetype: "Writer · whitepaper",
    badge: 5,
    allotted: true,
    cap: 8,
    load: 6,
    status: "active",
  },
  "0xa12...77df": {
    codename: "Anchor",
    archetype: "Builder · protocol",
    badge: 6,
    allotted: false,
    cap: 6,
    load: 5,
    status: "active",
  },
  "0x9f3...18ee": {
    codename: "Drift",
    archetype: "Researcher · alpha",
    badge: 7,
    allotted: false,
    cap: 5,
    load: 2,
    status: "quiet",
  },
};

export const projects = {
  pft_v3: {
    name: "PFT distribution v3",
    type: "Protocol development",
    summary: "Reward routing infrastructure rebuild. Adds parallel epoch settlement and verified reward distribution.",
    about:
      "Rebuild of the reward routing infrastructure underlying every task payout. Adds parallel epoch settlement, multi-tenant task race resolution, and a verified attestation path for reward distribution edge cases. Currently in phase 3 of 5, focused on edge case audits and operator-facing flows.",
    proposed: "Feb 14, 2026",
    phase: "3 of 5",
    pft: 420,
    contributors: [
      { wallet: "0x71f...4ab2", tasks: 4, pft: 86, lastActive: "6m ago", role: "lead" },
      { wallet: "0xb35...027e", tasks: 3, pft: 64, lastActive: "22m ago" },
      { wallet: "0xa12...77df", tasks: 3, pft: 72, lastActive: "3h ago" },
      { wallet: "0xc9e...d801", tasks: 2, pft: 48, lastActive: "1h ago" },
      { wallet: "0x10c...8a44", tasks: 1, pft: 22, lastActive: "1h ago" },
      { wallet: "0x9f3...18ee", tasks: 1, pft: 28, lastActive: "8h ago" },
    ],
    tasks: [
      {
        title: "Audit reward distribution edge case in epoch transitions",
        state: "proposed",
        assignee: "0x71f...4ab2",
        pft: 4.5,
        age: "awaiting accept",
      },
      { title: "Parallel settlement implementation", state: "accepted", assignee: "0xb35...027e", pft: 5.2, age: "day 3" },
      { title: "Multi-tenant task UI flows", state: "submitted", assignee: "0xc9e...d801", pft: 3.5, age: "day 1" },
      {
        title: "Verified reward attestation",
        state: "verification_requested",
        assignee: "0xa12...77df",
        pft: 6.0,
        age: "response needed",
      },
      {
        title: "Operator notification protocol",
        state: "verification_response",
        assignee: "0x10c...8a44",
        pft: 2.5,
        age: "awaiting decision",
      },
      { title: "Epoch-3 incident retrospective writeup", state: "paid", assignee: "0x71f...4ab2", pft: 3.0, age: "2d ago" },
      { title: "Race condition reproduction harness", state: "paid", assignee: "0xa12...77df", pft: 4.0, age: "4d ago" },
      { title: "Settlement latency benchmarks", state: "paid", assignee: "0xb35...027e", pft: 2.8, age: "5d ago" },
    ],
    activity: [
      { wallet: "0x71f...4ab2", action: "accepted", task: "Audit reward distribution edge case", time: "2m ago" },
      { wallet: "0xb35...027e", action: "submitted", task: "Parallel settlement implementation", time: "14m ago" },
      { wallet: "0xc9e...d801", action: "paid", task: "Multi-tenant task UI flows · v1", time: "1h ago", pft: 1.5 },
      { wallet: "0xa12...77df", action: "v_response", task: "Race condition reproduction harness", time: "3h ago" },
    ],
  },
  liquidity_v2: {
    name: "Cross-chain liquidity index",
    type: "Protocol development",
    summary: "Aggregating depth across 7 venues. Phase 2 of 4.",
    pft: 310,
    tasks: [],
    contributors: [],
  },
  onboarding: {
    name: "Operator onboarding redesign",
    type: "UX",
    summary: "Reworking the first 24 hours after a node joins.",
    pft: 45,
    tasks: [],
    contributors: [],
  },
  conf_q3: {
    name: "Conference circuit Q3",
    type: "Conference work",
    summary: "EthCC, Solana Breakpoint, Token2049 presence.",
    pft: 180,
    tasks: [],
    contributors: [],
  },
  whitepaper_v2: {
    name: "Whitepaper v2 research",
    type: "Whitepaper research",
    summary: "Empirical addendum and game theory section.",
    pft: 260,
    tasks: [],
    contributors: [],
  },
  alpha_weekly: {
    name: "Alpha digest weekly",
    type: "Alpha",
    summary: "Recurring. Market structure observations.",
    pft: 90,
    tasks: [],
    contributors: [],
  },
};

export const projectPreviewContributors = {
  pft_v3: ["0x71f...4ab2", "0xb35...027e", "0xa12...77df", "0xc9e...d801", "0x10c...8a44", "0x9f3...18ee"],
  liquidity_v2: ["0xb35...027e", "0xc9e...d801", "0xa12...77df", "0xf80...22bb", "0x9f3...18ee"],
  onboarding: ["0x42a...91fc", "0xf80...22bb"],
  conf_q3: ["0xf80...22bb", "0x10c...8a44", "0xc9e...d801"],
  whitepaper_v2: ["0x10c...8a44", "0x9f3...18ee", "0xc9e...d801", "0xa12...77df"],
  alpha_weekly: ["0xc9e...d801", "0x9f3...18ee"],
};

export const projectTaskCount = {
  pft_v3: 14,
  liquidity_v2: 9,
  onboarding: 3,
  conf_q3: 6,
  whitepaper_v2: 7,
  alpha_weekly: 4,
};

export const routingFeed = [
  { wallet: "0x71f...4ab2", action: "accepted", task: "Audit reward distribution edge case", project: "PFT distribution v3", time: "2m ago" },
  { wallet: "0xc9e...d801", action: "paid", task: "Draft EthCC sponsor outreach", project: "Conference circuit Q3", time: "6m ago", pft: 2.0 },
  { wallet: "0x42a...91fc", action: "proposed", task: "Profile messaging audit", project: "Operator onboarding", time: "14m ago", routing: "3 eligible" },
  { wallet: "0xb35...027e", action: "submitted", task: "Liquidity venue integration tests", project: "Cross-chain liquidity", time: "22m ago" },
  { wallet: "0x71f...4ab2", action: "paid", task: "Modal flow review", project: "UX hardening", time: "38m ago", pft: 1.8 },
  { wallet: "0xf80...22bb", action: "refused", task: "Discord moderation rota", project: "Community", time: "52m ago" },
  { wallet: "0x10c...8a44", action: "v_requested", task: "Whitepaper section 4 research", project: "Whitepaper v2 research", time: "1h ago" },
];

export function operatorForWallet(wallet) {
  return operators[wallet] || { codename: "—", archetype: "", badge: 0 };
}
