"""Initial setup

Revision ID: 9a4552b17277
Revises: 
Create Date: 2025-01-10 11:03:05.102231

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9a4552b17277'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('foundation_discord',
    sa.Column('hash', sa.String(length=255), nullable=False),
    sa.Column('memo_data', sa.Text(), nullable=True),
    sa.Column('memo_type', sa.String(length=255), nullable=True),
    sa.Column('memo_format', sa.String(length=255), nullable=True),
    sa.Column('datetime', sa.DateTime(), nullable=True),
    sa.Column('url', sa.Text(), nullable=True),
    sa.Column('directional_pft', sa.Float(), nullable=True),
    sa.Column('account', sa.String(length=255), nullable=True),
    sa.Column('processed_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('hash')
    )
    op.create_table('postfiat_tx_cache',
    sa.Column('hash', sa.String(length=255), nullable=False),
    sa.Column('close_time_iso', sa.String(length=255), nullable=True),
    sa.Column('ledger_hash', sa.String(length=255), nullable=True),
    sa.Column('ledger_index', sa.BigInteger(), nullable=True),
    sa.Column('meta', sa.Text(), nullable=True),
    sa.Column('tx_json', sa.Text(), nullable=True),
    sa.Column('validated', sa.Boolean(), nullable=True),
    sa.Column('account', sa.String(length=255), nullable=True),
    sa.Column('delivermax', sa.Text(), nullable=True),
    sa.Column('destination', sa.String(length=255), nullable=True),
    sa.Column('fee', sa.String(length=20), nullable=True),
    sa.Column('flags', sa.Float(), nullable=True),
    sa.Column('lastledgersequence', sa.BigInteger(), nullable=True),
    sa.Column('sequence', sa.BigInteger(), nullable=True),
    sa.Column('signingpubkey', sa.Text(), nullable=True),
    sa.Column('transactiontype', sa.String(length=50), nullable=True),
    sa.Column('txnsignature', sa.Text(), nullable=True),
    sa.Column('date', sa.BigInteger(), nullable=True),
    sa.Column('memos', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('hash')
    )
    op.create_index('idx_account_destination', 'postfiat_tx_cache', ['account', 'destination'], unique=False)
    op.create_index('idx_close_time_iso', 'postfiat_tx_cache', ['close_time_iso'], unique=False, postgresql_ops={'close_time_iso': 'DESC'})
    # ### end Alembic commands ###

    # create views manually for now, since alembic doesn't support views properly
    op.execute("""
            DROP VIEW IF EXISTS memo_detail_view;
            CREATE VIEW memo_detail_view AS
            WITH parsed_json AS (
                SELECT
                    *,
                    tx_json::jsonb as tx_json_parsed,
                    meta::jsonb as meta_parsed
                FROM postfiat_tx_cache
            ),
            memo_base AS (
                SELECT
                    *,
                    meta_parsed->>'TransactionResult' as transaction_result,
                    (tx_json_parsed->'Memos') IS NOT NULL as has_memos,
                    (close_time_iso::timestamp) as datetime,
                    COALESCE((tx_json_parsed->'DeliverMax'->>'value')::float, 0) as pft_absolute_amount,
                    (close_time_iso::timestamp)::date as simple_date,
                    (tx_json_parsed->'Memos'->0->'Memo') as main_memo_data
                FROM parsed_json
                WHERE (tx_json_parsed->'Memos') IS NOT NULL
            )
            SELECT * from memo_base;
    """)


def downgrade() -> None:
    op.execute("DROP VIEW IF EXISTS memo_detail_view;")

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_close_time_iso', table_name='postfiat_tx_cache', postgresql_ops={'close_time_iso': 'DESC'})
    op.drop_index('idx_account_destination', table_name='postfiat_tx_cache')
    op.drop_table('postfiat_tx_cache')
    op.drop_table('foundation_discord')
    # ### end Alembic commands ###

