services:
  api:
    environment:
      PFTL_WSS_URL: ${PFTL_WSS_URL:-wss://ws.testnet.postfiat.org}
      PFTL_WSS_URL_FALLBACKS: ${PFTL_WSS_URL_FALLBACKS:-}
      PFTL_WSS_REJECT_UNAUTHORIZED: "true"
      TASKNODE_ALLOW_INSECURE_LOCAL_PFTL_TLS: "false"
      PFTL_RPC_URL: ${PFTL_RPC_URL:-https://rpc.testnet.postfiat.org}
      PFTL_RPC_URL_FALLBACKS: ${PFTL_RPC_URL_FALLBACKS:-}
      PFTL_HISTORY_WSS_URL: ${PFTL_HISTORY_WSS_URL:-wss://ws-archive.testnet.postfiat.org}
      PFTL_HISTORY_RPC_URL: ${PFTL_HISTORY_RPC_URL:-https://rpc.testnet.postfiat.org:5006/}
      PFTL_CACHE_WSS_WATCHER_ENABLED: ${PFTL_CACHE_WSS_WATCHER_ENABLED:-true}
      PFTL_CACHE_WORKER_ENABLED: ${PFTL_CACHE_WORKER_ENABLED:-true}
      PFTL_CACHE_REDUCER_WORKER_ENABLED: ${PFTL_CACHE_REDUCER_WORKER_ENABLED:-true}
      PFTL_CACHE_ARCHIVE_WORKER_ENABLED: ${PFTL_CACHE_ARCHIVE_WORKER_ENABLED:-true}
      PFTL_CACHE_RETENTION_WORKER_ENABLED: ${PFTL_CACHE_RETENTION_WORKER_ENABLED:-true}
      ETH_DEPOSIT_RPC_URL: ${ETH_DEPOSIT_RPC_URL:-https://ethereum.publicnode.com}
