CREATE TABLE IF NOT EXISTS chat_conversations (
  id text PRIMARY KEY,
  account_id text NOT NULL DEFAULT '',
  title text NOT NULL DEFAULT 'New chat',
  status text NOT NULL DEFAULT 'active',
  mode text,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  last_message_at timestamptz,
  last_message_preview text NOT NULL DEFAULT '',
  message_count integer NOT NULL DEFAULT 0,
  deleted_at timestamptz
);

CREATE INDEX IF NOT EXISTS chat_conversations_account_recent_idx
  ON chat_conversations (account_id, status, updated_at DESC, id);

CREATE TABLE IF NOT EXISTS chat_messages (
  message_order bigint GENERATED BY DEFAULT AS IDENTITY,
  id text PRIMARY KEY,
  conversation_id text NOT NULL,
  account_id text NOT NULL DEFAULT '',
  role text NOT NULL,
  body text NOT NULL,
  mode text,
  provider text,
  model text,
  response_id text,
  created_at timestamptz NOT NULL DEFAULT now(),
  metadata_json jsonb NOT NULL DEFAULT '{}'::jsonb
);

CREATE INDEX IF NOT EXISTS chat_messages_conversation_recent_idx
  ON chat_messages (conversation_id, message_order DESC);

CREATE INDEX IF NOT EXISTS chat_messages_account_recent_idx
  ON chat_messages (account_id, message_order DESC);

CREATE TABLE IF NOT EXISTS chat_model_runs (
  id text PRIMARY KEY,
  conversation_id text NOT NULL,
  account_id text NOT NULL DEFAULT '',
  request_message_id text NOT NULL,
  response_message_id text NOT NULL,
  provider text NOT NULL,
  model text NOT NULL,
  mode text NOT NULL,
  response_id text,
  status text NOT NULL DEFAULT 'completed',
  input_tokens integer NOT NULL DEFAULT 0,
  output_tokens integer NOT NULL DEFAULT 0,
  total_tokens integer NOT NULL DEFAULT 0,
  web_search_calls integer NOT NULL DEFAULT 0,
  tool_cost_usd numeric(18, 6) NOT NULL DEFAULT 0,
  model_cost_usd numeric(18, 6) NOT NULL DEFAULT 0,
  total_cost_usd numeric(18, 6) NOT NULL DEFAULT 0,
  started_at timestamptz NOT NULL DEFAULT now(),
  completed_at timestamptz,
  error text,
  metadata_json jsonb NOT NULL DEFAULT '{}'::jsonb
);

CREATE INDEX IF NOT EXISTS chat_model_runs_account_recent_idx
  ON chat_model_runs (account_id, started_at DESC, id);

CREATE TABLE IF NOT EXISTS billing_accounts (
  account_id text PRIMARY KEY,
  currency text NOT NULL DEFAULT 'USD',
  status text NOT NULL DEFAULT 'active',
  current_spend_usd numeric(18, 6) NOT NULL DEFAULT 0,
  current_credit_usd numeric(18, 6) NOT NULL DEFAULT 0,
  ledger_entry_count integer NOT NULL DEFAULT 0,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS billing_ledger_entries (
  id text PRIMARY KEY,
  account_id text NOT NULL DEFAULT '',
  kind text NOT NULL,
  amount_usd numeric(18, 6) NOT NULL,
  source text NOT NULL DEFAULT '',
  note text NOT NULL DEFAULT '',
  created_by text NOT NULL DEFAULT 'system',
  conversation_id text,
  model_run_id text,
  provider text,
  model text,
  mode text,
  response_id text,
  input_tokens integer NOT NULL DEFAULT 0,
  output_tokens integer NOT NULL DEFAULT 0,
  total_tokens integer NOT NULL DEFAULT 0,
  web_search_calls integer NOT NULL DEFAULT 0,
  tool_cost_usd numeric(18, 6) NOT NULL DEFAULT 0,
  idempotency_key text,
  metadata_json jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE UNIQUE INDEX IF NOT EXISTS billing_ledger_entries_idempotency_key_idx
  ON billing_ledger_entries (idempotency_key)
  WHERE idempotency_key IS NOT NULL;

CREATE INDEX IF NOT EXISTS billing_ledger_entries_account_recent_idx
  ON billing_ledger_entries (account_id, created_at DESC, id);

CREATE INDEX IF NOT EXISTS billing_ledger_entries_conversation_recent_idx
  ON billing_ledger_entries (conversation_id, created_at DESC, id)
  WHERE conversation_id IS NOT NULL;

