---
- name: Deploy Task Node
  hosts: task-node-with-db-4
  become: yes
  vars_files:
    - group_vars/all/common.yml
    - "group_vars/all/{{ network }}.yml"
  
  pre_tasks:
    - name: Update dnf cache
      dnf:
        update_cache: yes

  roles:
    - role: common
      when: full_deploy | default(false) | bool
    - role: python
      when: full_deploy | default(false) | bool
    - role: postgres
      when: full_deploy | default(false) | bool
    - tasknode 