---
- name: Deploy Task Node
  hosts: "{{ target_hosts }}"
  become: yes
  vars_files:
    - "group_vars/all/{{ network }}.yml"
  
  pre_tasks:
    - name: Update dnf cache
      dnf:
        update_cache: yes

  roles:
    - role: common
      when: full_deploy | default(false) | bool
    - role: python
      when: full_deploy | default(false) | bool
    - role: postgres
      when: full_deploy | default(false) | bool
#    - role: tasknode
#      when: full_deploy | default(false) | bool
#    - role: tasknode
#      when: not full_deploy | default(false) | bool
#      tasks:
#        - import_tasks: roles/tasknode/tasks/install_code.yml
