---
- name: Deploy Task Node
  hosts: task-node-1
  become: yes
  
  pre_tasks:
    - name: Update dnf cache
      dnf:
        update_cache: yes

  roles:
    - common
    - python
    - postgres
    - tasknode 