---
all:
  children:
    tasknode:
      children:
        mainnet:
          hosts:
            task-node-1:
              ansible_host: ec2-3-14-1-201.us-east-2.compute.amazonaws.com
          vars:
            network: mainnet
        testnet:
          hosts:
            task-node-with-db:
              ansible_host: ec2-18-223-159-228.us-east-2.compute.amazonaws.com
            task-node-with-db-2:
              ansible_host: ec2-18-119-120-62.us-east-2.compute.amazonaws.com
            task-node-with-db-3:
              ansible_host: ec2-52-14-237-100.us-east-2.compute.amazonaws.com
          vars:
            network: testnet
      vars:
        ansible_python_interpreter: /usr/bin/python3
        ansible_user: ec2-user
