---
all:
  children:
    tasknode:
      children:
        mainnet:
          hosts:
            task-node-1:
              ansible_host: ec2-3-14-1-201.us-east-2.compute.amazonaws.com
          vars:
            network: mainnet
        testnet:
          hosts:
            task-node-with-db:
              ansible_host: ec2-18-222-49-204.us-east-2.compute.amazonaws.com
          vars:
            network: testnet
      vars:
        ansible_python_interpreter: /usr/bin/python3
        ansible_user: ec2-user