---
all:
  children:
    tasknode:
      children:
        mainnet:
          hosts:
            task-node-prod:
              ansible_host: ec2-3-137-171-164.us-east-2.compute.amazonaws.com
              postgres_host: task-node-db-prod.ctuy80uk08cm.us-east-2.rds.amazonaws.com
              network: mainnet
        testnet:
          hosts:
            task-node-dev:
              ansible_host: ec2-3-145-2-106.us-east-2.compute.amazonaws.com
              postgres_host: task-node-db-dev.ctuy80uk08cm.us-east-2.rds.amazonaws.com
              network: testnet
      vars:
        ansible_python_interpreter: /usr/bin/python3
        ansible_user: ec2-user
