---
#- name: Run nodetools init-db in auto mode
#  command: "{{ app_dir }}/.venv/bin/nodetools init-db"
#  environment:
#    AUTO: "1"
#    ENCRYPTION_PASSWORD: "{{ encryption_password }}"
#    NETWORK: "{{ network }}"
#  become: yes
#  become_user: "{{ app_user }}"

#- name: Copy database initialization script
#  template:
#    src: templates/init_db.sql.j2
#    dest: "/tmp/init_db.sql"
#    owner: "{{ postgres_master_user }}"
#    mode: '0644'

- name: Execute database initialization script
  postgresql_query:
    db: "{{ postgres_db }}"
    query: "{{ lookup('template', 'templates/init_db.sql.j2') }}"
  become: yes
  become_user: "{{ postgres_master_user }}"

#- name: Remove initialization script
#  file:
#    path: "/tmp/init_db.sql"
#    state: absent
