---
- name: Remove existing TaskNode directory
  file:
    path: "{{ app_dir }}"
    state: absent
  become: yes

- name: Clone TaskNode repository
  git:
    repo: "{{ repo }}"
    dest: "{{ app_dir }}"
    version: "{{ branch }}"
  become_user: "{{ app_user }}"

- name: Create Python virtual environment
  command:
    cmd: python3.12 -m venv "{{ app_dir }}/.venv"
  become_user: "{{ app_user }}"

- name: Install project as package
  command: "{{ app_dir }}/.venv/bin/python -m pip install -e {{ app_dir }}"
  become_user: "{{ app_user }}"

- name: Restart TaskNode service
  systemd:
    name: tasknode
    state: restarted
  tags:
    - force_restart
