---
- name: Create node configs (setup-node)
  import_tasks: setup_node.yml

- name: Create tasknode config directory
  file:
    path: "/etc/tasknode"
    state: directory
    owner: root
    group: root
    mode: '0755'
  become: yes

- name: Create environment file
  template:
    src: env.j2
    dest: "/etc/tasknode/.env"
    owner: root
    group: root
    mode: '0600'
  become: yes

- name: Create systemd service file
  template:
    src: tasknode.service.j2
    dest: /etc/systemd/system/tasknode.service
    owner: root
    group: root
    mode: '0644'
  notify: restart tasknode

- name: Enable and start TaskNode service
  systemd:
    name: tasknode
    enabled: yes
    state: restarted
    daemon_reload: yes
  tags:
    - force_restart
