---
- name: Remove existing TaskNode directory
  file:
    path: "{{ app_dir }}"
    state: absent
  become: yes

- name: Clone TaskNode repository
  git:
    repo: "{{ repo }}"
    dest: "{{ app_dir }}"
    version: "{{ branch }}"
  become_user: "{{ app_user }}"

- name: Install project as package
  pip:
    name: "{{ app_dir }}"
    virtualenv: "{{ app_dir }}/venv"
    virtualenv_python: python3
    editable: true
  become_user: "{{ app_user }}"

- name: Create environment file
  template:
    src: env.j2
    dest: "{{ app_dir }}/.env"
    owner: "{{ app_user }}"
    group: "{{ app_group }}"
    mode: '0600'

- name: Run local setup node tasks
  import_tasks: setup_node.yml

- name: Run local postgres installation tasks
  import_tasks: init_db.yml

- name: Create systemd service file
  template:
    src: tasknode.service.j2
    dest: /etc/systemd/system/tasknode.service
    owner: root
    group: root
    mode: '0644'
  notify: restart tasknode

- name: Enable and start TaskNode service
  systemd:
    name: tasknode
    enabled: yes
    state: started
    daemon_reload: yes