---
- name: Clone TaskNode repository
  git:
    repo: "https://github.com/postfiatorg/tasknode.git"
    dest: {{ app_dir }}/app
    version: main # TODO: variable
  become_user: "{{ app_user }}"

- name: Install project dependencies
  pip:
    requirements: {{ app_dir }}/app/requirements.txt
    virtualenv: {{ app_dir }}/venv
    virtualenv_python: python3
  become_user: "{{ app_user }}"

- name: Create environment file
  template:
    src: env.j2
    dest: {{ app_dir }}/.env
    owner: "{{ app_user }}"
    group: "{{ app_group }}"
    mode: '0600'

- name: Create systemd service file
  template:
    src: tasknode.service.j2
    dest: /etc/systemd/system/tasknode.service
    owner: root
    group: root
    mode: '0644'
  notify: restart tasknode

- name: Enable and start TaskNode service
  systemd:
    name: tasknode
    enabled: yes
    state: started
    daemon_reload: yes