---
ansible_user: ec2-user

# app deployment
repo: https://github.com/postfiatorg/tasknode.git
branch: john/basic-aws-deploy

# postgres common settings
postgres_host: localhost
postgres_port: 5432
postgres_user: postfiat
postgres_conn_string: postgres://{{ postgres_user }}:{{ postgres_password }}@{{ postgres_host }}:{{ postgres_port }}/{{ postgres_db }}
postgres_master_user: postgres

# System Configuration
app_user: ec2-user
app_group: ec2-user
#app_dir: /opt/tasknode/app
app_dir: /home/ec2-user/tasknode
log_level: INFO