---
network: testnet
discord_server_id: 510536760367906818
discord_activity_channel_id: 1330388703410917489
postgres_db: postfiat_db
discord_bot_token: "{{ discord_bot_token_testnet }}"
task_node_wallet: "{{ task_node_wallet_testnet }}"
remembrancer_wallet: "{{ remembrancer_wallet_testnet }}"
postgres_password: "{{ postgres_password_testnet }}"
postgres_master_password: "{{ postgres_master_password_testnet }}"
encryption_password: "{{ encryption_password_testnet }}"
