---
- name: Install Python packages
  apt:
    name:
      - python3
      - python3-pip
      - python3-dev
      - python3-venv
    state: present

- name: Upgrade pip
  pip:
    name: pip
    state: latest
    executable: pip3

- name: Create project directory
  file:
    path: "{{ app_dir }}"
    state: directory
    owner: "{{ app_user }}"
    group: "{{ app_group }}"
    mode: '0755'

- name: Create Python virtual environment
  command:
    cmd: python3 -m venv {{ app_dir }}/venv
    creates: {{ app_dir }}/venv
  become_user: "{{ app_user }}"
